:dizzy: WAT!...
[Logs](https://github.com/S0AndS0/dockerized-charmbracelet_freeze/actions/runs/15788391270/job/44509594543)
now say tags were checked-out by `actions/checkout` so re-checking-out
is rejected?!  Not impressed, but commenting-out configs causing errors.

```
Run git fetch --prune --unshallow --tags

From https://github.com/S0AndS0/dockerized-charmbracelet_freeze
 * [new branch]      main       -> origin/main
 * [new tag]         v0.0.1     -> v0.0.1
 * [new tag]         v0.0.2     -> v0.0.2
 * [new tag]         v0.0.3     -> v0.0.3
 * [new tag]         v0.0.4     -> v0.0.4
 * [new tag]         v0.0.5     -> v0.0.5
 * [new tag]         v0.0.6     -> v0.0.6
 * [new tag]         v0.0.7     -> v0.0.7
 ! [rejected]        v0.0.8     -> v0.0.8  (would clobber existing tag)
Error: Process completed with exit code 1.
```